     repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
        -   id: check-ast
        -   id: check-byte-order-marker
        -   id: check-case-conflict
        -   id: check-json
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: mixed-line-ending
        -   id: check-added-large-files
        -   id: check-merge-conflict
        -   id: pretty-format-json
      - repo: local
        hooks:
          - id: black
            name: black
            language: system
            entry: poetry run black src tests
            always_run: true
            pass_filenames: false


          - id: flake8
            name: flake8
            language: system
            entry: poetry run flake8 src tests
            always_run: true
            pass_filenames: false

          - id: mypy
            name: mypy
            language: system
            entry: poetry run mypy src tests
            always_run: true
            pass_filenames: false
